#pragma once

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  SEQ_UNIT_ORIGINAL,
  SEQ_UNIT_MNEMONIC,
  SEQ_UNIT_OPCODE,
} SEQ_UNITS;

typedef enum {
  SEQ_UNITINFO_IS_CALL,
  SEQ_UNITINFO_IS_JMP,
  SEQ_UNITINFO_BRANCH_TO,
  SEQ_UNITINFO_INST_LENGTH,
  SEQ_UNITINFO_ACCESS_VIOLATION,
} SEQ_UNITINFO_CONSTS;

typedef enum {
  SEQ_UNITINFO_VALUE_ACCESS_VIOLATION_NONE,
  SEQ_UNITINFO_VALUE_ACCESS_VIOLATION_READ,
  SEQ_UNITINFO_VALUE_ACCESS_VIOLATION_WRITE,
} SEQ_UNITINFO_VALUE_ACCESS_VIOLATION;

#ifdef __cplusplus
}
#endif
